### ISSUE TITLE
MI 7 pro Android 10 - Crashing issue, ChatDomain.Builder::build() must be called before obtaining ChatDomain instance

### ISSUE THREAD

**Issue by livingstonantony70** [philipplackner/StreamChatApp#1]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.plcoding.streamchatapp, PID: 8441
    java.lang.IllegalStateException: ChatDomain.Builder::build() must be called before obtaining ChatDomain instance
       at com.plcoding.streamchatapp.ui.channel.ChannelFragment.onViewCreated$lambda-1(ChannelFragment.kt:45)
        at com.plcoding.streamchatapp.ui.channel.ChannelFragment.onViewCreated(ChannelFragment.kt:47)
```

**Here is my Code**

 ```
val factory = ChannelListViewModelFactory(
            filter = Filters.and(
                Filters.eq("type", "messaging"),
            ),
            sort = ChannelListViewModel.DEFAULT_SORT,
            limit = 30
        )
        val channelListViewModel: ChannelListViewModel by viewModels { factory }
        val channelListHeaderViewModel: ChannelListHeaderViewModel by viewModels()
        channelListViewModel.bindView(binding.channelListView, viewLifecycleOwner)
        channelListHeaderViewModel.bindView(binding.channelListHeaderView, viewLifecycleOwner)
```
**Full Code of ChannelFragment.kt**

```
package com.plcoding.streamchatapp.ui.channel


import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import androidx.fragment.app.activityViewModels
import androidx.fragment.app.viewModels
import androidx.navigation.fragment.findNavController
import androidx.viewbinding.ViewBinding
import com.plcoding.streamchatapp.databinding.FragmentChannelBinding
import com.plcoding.streamchatapp.ui.BindingFragment
import dagger.hilt.android.AndroidEntryPoint
import io.getstream.chat.android.client.models.Filters
import io.getstream.chat.android.ui.channel.list.header.viewmodel.ChannelListHeaderViewModel
import io.getstream.chat.android.ui.channel.list.header.viewmodel.bindView
import io.getstream.chat.android.ui.channel.list.viewmodel.ChannelListViewModel
import io.getstream.chat.android.ui.channel.list.viewmodel.bindView
import io.getstream.chat.android.ui.channel.list.viewmodel.factory.ChannelListViewModelFactory

@AndroidEntryPoint
class ChannelFragment : BindingFragment<FragmentChannelBinding>() {

    override val bindingInflater: (LayoutInflater) -> ViewBinding
        get() = FragmentChannelBinding::inflate

    private val viewModel: ChannelViewModel by activityViewModels()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val user = viewModel.getUser()
        if(user == null) {
            findNavController().popBackStack()
            return
        }

        val factory = ChannelListViewModelFactory(
            filter = Filters.and(
                Filters.eq("type", "messaging"),
            ),
            sort = ChannelListViewModel.DEFAULT_SORT,
            limit = 30
        )
        val channelListViewModel: ChannelListViewModel by viewModels { factory }
        val channelListHeaderViewModel: ChannelListHeaderViewModel by viewModels()
        channelListViewModel.bindView(binding.channelListView, viewLifecycleOwner)
        channelListHeaderViewModel.bindView(binding.channelListHeaderView, viewLifecycleOwner)

        binding.channelListHeaderView.setOnUserAvatarClickListener {
            viewModel.logout()
            findNavController().popBackStack()
        }
    }
}
```

**Comment by livingstonantony70** [comment]
I cloned code from GitHub that's working fine, I do not know where  I done mistake :-(

**Comment by polataydinn** [comment]
@livin-bad I  had the same issue so i changed the get-stream version to "4.12.1" now it works fine.
